# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghstat < Formula
  desc "Statistical multi-criteria comparator for GitHub projects."
  homepage "https://github.com/fedir/ghstat"
  version "0.8.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fedir/ghstat/releases/download/v0.8.0/ghstat_0.8.0_darwin_amd64.tar.gz"
      sha256 "1efd7acca57460185b55d7f6458521630527738b182a3cba438da5b39eef0b3e"

      define_method(:install) do
        bin.install "ghstat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fedir/ghstat/releases/download/v0.8.0/ghstat_0.8.0_darwin_arm64.tar.gz"
      sha256 "362bbe6e71d5c493e70833f0785b00de733c61074d1d8568eecd6ca7deb8605c"

      define_method(:install) do
        bin.install "ghstat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fedir/ghstat/releases/download/v0.8.0/ghstat_0.8.0_linux_amd64.tar.gz"
      sha256 "c0a52c2e758fe37defc67d202e01170735c721869d776f1700e2b03d88cffd0d"
      define_method(:install) do
        bin.install "ghstat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fedir/ghstat/releases/download/v0.8.0/ghstat_0.8.0_linux_arm64.tar.gz"
      sha256 "ec9802fa2128e6d48d1eb5c5e7e5be6933c626244b340f70163dd092e192ddec"
      define_method(:install) do
        bin.install "ghstat"
      end
    end
  end

  test do
    assert_match "ghstat", shell_output("#{bin}/ghstat -version")
  end
end
