# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JsonEncode < Formula
  desc "Turn any shell output into JSON, one pipe away."
  homepage "https://github.com/fedir/json_encode"
  version "2.0.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fedir/json_encode/releases/download/v2.0.0/json_encode_2.0.0_darwin_amd64.tar.gz"
      sha256 "9d5f0a86018a2c0596dcbb12ba7c8710c4c6d16a70161c4e512307ca4f7cc307"

      define_method(:install) do
        bin.install "json_encode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fedir/json_encode/releases/download/v2.0.0/json_encode_2.0.0_darwin_arm64.tar.gz"
      sha256 "bcb5dcc7d71f9c9282073ac408f966f05b9e1828017608c10ac66d390b52661e"

      define_method(:install) do
        bin.install "json_encode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fedir/json_encode/releases/download/v2.0.0/json_encode_2.0.0_linux_amd64.tar.gz"
      sha256 "e55fa1657b8a2e2639e1563363abf79536e58c909bc4b77efd971d64e3cfeb50"
      define_method(:install) do
        bin.install "json_encode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fedir/json_encode/releases/download/v2.0.0/json_encode_2.0.0_linux_arm64.tar.gz"
      sha256 "19d4ebab6cdc014dee88b9d26db61800f4eeea7e2774980d17b8f9670ff4bdac"
      define_method(:install) do
        bin.install "json_encode"
      end
    end
  end

  test do
    assert_match "json_encode", shell_output("#{bin}/json_encode -version")
  end
end
