# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yrank < Formula
  desc "Rank YouTube playlist, channel or search-result videos by engagement metrics."
  homepage "https://github.com/fedir/yrank"
  version "0.2.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fedir/yrank/releases/download/v0.2.0/yrank_0.2.0_darwin_amd64.tar.gz"
      sha256 "e25f0daee4b9799e5d7787ad912c949d2cfb6265d93e69f263b04b96f49fd501"

      define_method(:install) do
        bin.install "yrank"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fedir/yrank/releases/download/v0.2.0/yrank_0.2.0_darwin_arm64.tar.gz"
      sha256 "cc651f15be5b4c0c8322a19fe9fa39b9873b4c49ebcb06826fac4da939c13e95"

      define_method(:install) do
        bin.install "yrank"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fedir/yrank/releases/download/v0.2.0/yrank_0.2.0_linux_amd64.tar.gz"
      sha256 "729094269cc49815677cba3d756cf35e8923e8508473cfc4be6e64a3fda16d31"
      define_method(:install) do
        bin.install "yrank"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fedir/yrank/releases/download/v0.2.0/yrank_0.2.0_linux_arm64.tar.gz"
      sha256 "1dae5c8787a13d3cb5210250d7d4ba7b6c3429c07e38368e442c18d0229b7b27"
      define_method(:install) do
        bin.install "yrank"
      end
    end
  end

  test do
    assert_match "yrank", shell_output("#{bin}/yrank -version")
  end
end
