# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yrank < Formula
  desc "Rank YouTube playlist, channel or search-result videos by engagement metrics."
  homepage "https://github.com/fedir/yrank"
  version "0.3.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fedir/yrank/releases/download/v0.3.0/yrank_0.3.0_darwin_amd64.tar.gz"
      sha256 "eeb37b8fd589ad04423b6cf32ce4ddb3247fb410ec17eb6add5aa484b232e806"

      define_method(:install) do
        bin.install "yrank"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fedir/yrank/releases/download/v0.3.0/yrank_0.3.0_darwin_arm64.tar.gz"
      sha256 "cbc4d691cbc8766254bf63bce20a64077e88fd104ca13f05866a5bdda1145ce8"

      define_method(:install) do
        bin.install "yrank"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fedir/yrank/releases/download/v0.3.0/yrank_0.3.0_linux_amd64.tar.gz"
      sha256 "82bd16463ef6abfc9332c339d7902eedef40488efd11136c8002875f91a921bd"
      define_method(:install) do
        bin.install "yrank"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fedir/yrank/releases/download/v0.3.0/yrank_0.3.0_linux_arm64.tar.gz"
      sha256 "61105aa8004499c4f674295ab0a826eb05008ab8dcdd8ac25fb99b5c0ce9bdd0"
      define_method(:install) do
        bin.install "yrank"
      end
    end
  end

  test do
    assert_match "yrank", shell_output("#{bin}/yrank -version")
  end
end
